[[hiragana]]
character = "あ"
romaji = "a"

[[hiragana]]
character = "い"
romaji = "i"

[[hiragana]]
character = "う"
romaji = "u"

[[hiragana]]
character = "え"
romaji = "e"

[[hiragana]]
character = "お"
romaji = "o"

[[hiragana]]
character = "か"
romaji = "ka"

[[hiragana]]
character = "き"
romaji = "ki"

[[hiragana]]
character = "く"
romaji = "ku"

[[hiragana]]
character = "け"
romaji = "ke"

[[hiragana]]
character = "こ"
romaji = "ko"

[[hiragana]]
character = "さ"
romaji = "sa"

[[hiragana]]
character = "し"
romaji = "shi"

[[hiragana]]
character = "す"
romaji = "su"

[[hiragana]]
character = "せ"
romaji = "se"

[[hiragana]]
character = "そ"
romaji = "so"

[[hiragana]]
character = "た"
romaji = "ta"

[[hiragana]]
character = "ち"
romaji = "chi"

[[hiragana]]
character = "つ"
romaji = "tsu"

[[hiragana]]
character = "て"
romaji = "te"

[[hiragana]]
character = "と"
romaji = "to"

[[hiragana]]
character = "な"
romaji = "na"

[[hiragana]]
character = "に"
romaji = "ni"

[[hiragana]]
character = "ぬ"
romaji = "nu"

[[hiragana]]
character = "ね"
romaji = "ne"

[[hiragana]]
character = "の"
romaji = "no"

[[hiragana]]
character = "は"
romaji = "ha"

[[hiragana]]
character = "ひ"
romaji = "hi"

[[hiragana]]
character = "ふ"
romaji = "fu"

[[hiragana]]
character = "へ"
romaji = "he"

[[hiragana]]
character = "ほ"
romaji = "ho"

[[hiragana]]
character = "ま"
romaji = "ma"

[[hiragana]]
character = "み"
romaji = "mi"

[[hiragana]]
character = "む"
romaji = "mu"

[[hiragana]]
character = "め"
romaji = "me"

[[hiragana]]
character = "も"
romaji = "mo"

[[hiragana]]
character = "や"
romaji = "ya"

[[hiragana]]
character = "ゆ"
romaji = "yu"

[[hiragana]]
character = "よ"
romaji = "yo"

[[hiragana]]
character = "ら"
romaji = "ra"

[[hiragana]]
character = "り"
romaji = "ri"

[[hiragana]]
character = "る"
romaji = "ru"

[[hiragana]]
character = "れ"
romaji = "re"

[[hiragana]]
character = "ろ"
romaji = "ro"

[[hiragana]]
character = "わ"
romaji = "wa"

[[hiragana]]
character = "を"
romaji = "wo"

[[hiragana]]
character = "ん"
romaji = "n"
