[[hiragana]]
character = "が"
romaji = "ga"

[[hiragana]]
character = "ぎ"
romaji = "gi"

[[hiragana]]
character = "ぐ"
romaji = "gu"

[[hiragana]]
character = "げ"
romaji = "ge"

[[hiragana]]
character = "ご"
romaji = "go"

[[hiragana]]
character = "ざ"
romaji = "za"

[[hiragana]]
character = "じ"
romaji = "ji"

[[hiragana]]
character = "ず"
romaji = "zu"

[[hiragana]]
character = "ぜ"
romaji = "ze"

[[hiragana]]
character = "ぞ"
romaji = "zo"

[[hiragana]]
character = "だ"
romaji = "da"

[[hiragana]]
character = "ぢ"
romaji = "ji"   # Rarely used

[[hiragana]]
character = "づ"
romaji = "zu"   # Rarely used

[[hiragana]]
character = "で"
romaji = "de"

[[hiragana]]
character = "ど"
romaji = "do"

[[hiragana]]
character = "ば"
romaji = "ba"

[[hiragana]]
character = "び"
romaji = "bi"

[[hiragana]]
character = "ぶ"
romaji = "bu"

[[hiragana]]
character = "べ"
romaji = "be"

[[hiragana]]
character = "ぼ"
romaji = "bo"
