[[hiragana]]
character = "ぱ"
romaji = "pa"

[[hiragana]]
character = "ぴ"
romaji = "pi"

[[hiragana]]
character = "ぷ"
romaji = "pu"

[[hiragana]]
character = "ぺ"
romaji = "pe"

[[hiragana]]
character = "ぽ"
romaji = "po"
