[[translations]]
japanese_word = "浴びる"
romaji = "abiru"
english_translation = "to bathe, to shower"
category = "Verb"

[[translations]]
japanese_word = "危ない"
romaji = "abunai"
english_translation = "dangerous"
category = "Adjective"

[[translations]]
japanese_word = "あっち"
romaji = "acchi"
english_translation = "over there"
category = "Pronoun"

[[translations]]
japanese_word = "あちら"
romaji = "achira"
english_translation = "there"
category = "Pronoun"

[[translations]]
japanese_word = "上げる"
romaji = "ageru"
english_translation = "to raise; to elevate; to give"
category = "Verb"

[[translations]]
japanese_word = "赤"
romaji = "aka"
english_translation = "red; crimson; scarlet"
category = "Noun"

[[translations]]
japanese_word = "赤い"
romaji = "akai"
english_translation = "red; crimson; scarlet"
category = "Adjective"

[[translations]]
japanese_word = "明るい"
romaji = "akarui"
english_translation = "bright; light"
category = "Adjective"

[[translations]]
japanese_word = "開ける"
romaji = "akeru"
english_translation = "to open (a door, etc.); to unwrap; to unlock"
category = "Verb"

[[translations]]
japanese_word = "秋"
romaji = "aki"
english_translation = "autumn; fall"
category = "Time"

[[translations]]
japanese_word = "開く"
romaji = "aku"
english_translation = "to open (e.g. doors, business, etc.)"
category = "Verb"

[[translations]]
japanese_word = "甘い"
romaji = "amai"
english_translation = "sweet; sugary; naive; indulgent"
category = "Adjective"

[[translations]]
japanese_word = "雨"
romaji = "ame"
english_translation = "rain"
category = "Noun"

[[translations]]
japanese_word = "飴"
romaji = "ame"
english_translation = "candy"
category = "Noun"

[[translations]]
japanese_word = "あなた"
romaji = "anata"
english_translation = "you"
category = "Pronoun"

[[translations]]
japanese_word = "姉"
romaji = "ane"
english_translation = "older sister; elder sister"
category = "Noun"

[[translations]]
japanese_word = "兄"
romaji = "ani"
english_translation = "elder brother; older brother"
category = "Noun"

[[translations]]
japanese_word = "あの"
romaji = "ano"
english_translation = "that"
category = "PreNounAdjectival"

[[translations]]
japanese_word = "青"
romaji = "ao"
english_translation = "blue; azure"
category = "Noun"

[[translations]]
japanese_word = "青い"
romaji = "aoi"
english_translation = "blue; azure"
category = "Adjective"

[[translations]]
japanese_word = "アパート"
romaji = "apaato"
english_translation = "apartment"
category = "Noun"

[[translations]]
japanese_word = "洗う"
romaji = "arau"
english_translation = "to wash"
category = "Verb"

[[translations]]
japanese_word = "あれ"
romaji = "are"
english_translation = "that"
category = "Pronoun"

[[translations]]
japanese_word = "ある"
romaji = "aru"
english_translation = "to be, to have"
category = "Verb"

[[translations]]
japanese_word = "歩く"
romaji = "aruku"
english_translation = "to walk"
category = "Verb"

[[translations]]
japanese_word = "朝"
romaji = "asa"
english_translation = "morning"
category = "Time"

[[translations]]
japanese_word = "朝ご飯"
romaji = "asagohan"
english_translation = "breakfast"
category = "Noun"

[[translations]]
japanese_word = "明後日"
romaji = "asatte"
english_translation = "day after tomorrow"
category = "Time"

[[translations]]
japanese_word = "足"
romaji = "ashi"
english_translation = "foot; leg; paw; arm"
category = "Noun"

[[translations]]
japanese_word = "明日"
romaji = "ashita"
english_translation = "tomorrow"
category = "Time"

[[translations]]
japanese_word = "遊ぶ"
romaji = "asobu"
english_translation = "to play; to enjoy oneself"
category = "Verb"

[[translations]]
japanese_word = "あそこ"
romaji = "asoko"
english_translation = "over there"
category = "Pronoun"

[[translations]]
japanese_word = "頭"
romaji = "atama"
english_translation = "head"
category = "Noun"

[[translations]]
japanese_word = "新しい"
romaji = "atarashii"
english_translation = "new; novel; fresh; recent"
category = "Adjective"

[[translations]]
japanese_word = "暖かい"
romaji = "atatakai"
english_translation = "warm"
category = "Adjective"

[[translations]]
japanese_word = "後"
romaji = "ato"
english_translation = "behind; after; remainder; left; also"
category = "Noun"

[[translations]]
japanese_word = "暑い"
romaji = "atsui"
english_translation = "hot; sultry"
category = "Adjective"

[[translations]]
japanese_word = "厚い"
romaji = "atsui"
english_translation = "thick"
category = "Adjective"

[[translations]]
japanese_word = "熱い"
romaji = "atsui"
english_translation = "hot"
category = "Adjective"

[[translations]]
japanese_word = "会う"
romaji = "au"
english_translation = "to meet; to encounter; to see"
category = "Verb"

[[translations]]
japanese_word = "晩ご飯"
romaji = "bangohan"
english_translation = "dinner; evening meal"
category = "Noun"

[[translations]]
japanese_word = "番号"
romaji = "bangou"
english_translation = "number"
category = "Noun"

[[translations]]
japanese_word = "バス"
romaji = "basu"
english_translation = "bus"
category = "Noun"

[[translations]]
japanese_word = "バター"
romaji = "bataa"
english_translation = "butter"
category = "Noun"

[[translations]]
japanese_word = "ベッド"
romaji = "beddo"
english_translation = "bed"
category = "Noun"

[[translations]]
japanese_word = "勉強"
romaji = "benkyou"
english_translation = "to study"
category = "SuruVerb"

[[translations]]
japanese_word = "便利"
romaji = "benri"
english_translation = "convenient; handy; useful"
category = "Adjective"

[[translations]]
japanese_word = "ボールペン"
romaji = "boorupen"
english_translation = "ball-point pen"
category = "Noun"

[[translations]]
japanese_word = "ボタン"
romaji = "botan"
english_translation = "button"
category = "Noun"

[[translations]]
japanese_word = "帽子"
romaji = "boushi"
english_translation = "hat; cap"
category = "Noun"

[[translations]]
japanese_word = "文章"
romaji = "bunshou"
english_translation = "sentence"
category = "Noun"

[[translations]]
japanese_word = "豚肉"
romaji = "butaniku"
english_translation = "pork"
category = "Noun"

[[translations]]
japanese_word = "病院"
romaji = "byouin"
english_translation = "hospital"
category = "Noun"

[[translations]]
japanese_word = "病気"
romaji = "byouki"
english_translation = "illness; disease; sickness"
category = "Noun"
