[[translations]]
japanese_word = "もっと低い"
romaji = "motto hikui"
english_translation = "more lower"
category = "Adjective"

[[translations]]
japanese_word = "とても"
romaji = "totemo"
english_translation = "really/very"
category = "Adjective"

[[translations]]
japanese_word = "賢い"
romaji = "kashikoi"
english_translation = "clever/smart"
category = "Adjective"

[[translations]]
japanese_word = "速く"
romaji = "hayaku"
english_translation = "faster/quickly"
category = "Adjective"

[[translations]]
japanese_word = "高い"
romaji = "takai"
english_translation = "expensive or tall"
category = "Adjective"

[[translations]]
japanese_word = "難しい"
romaji = "muzukashii"
english_translation = "difficult"
category = "Adjective"

[[translations]]
japanese_word = "楽しい"
romaji = "tanoshii"
english_translation = "fun"
category = "Adjective"

[[translations]]
japanese_word = "怖い"
romaji = "kowai"
english_translation = "scary"
category = "Adjective"

[[translations]]
japanese_word = "可愛い"
romaji = "kawaii"
english_translation = "cute"
category = "Adjective"

[[translations]]
japanese_word = "悲しい"
romaji = "kanashii"
english_translation = "sad"
category = "Adjective"

[[translations]]
japanese_word = "新しい"
romaji = "atarashii"
english_translation = "new"
category = "Adjective"

[[translations]]
japanese_word = "嬉しい"
romaji = "ureshii"
english_translation = "glad"
category = "Adjective"

[[translations]]
japanese_word = "合っている"
romaji = "atteiru"
english_translation = "correct"
category = "Adjective"

[[translations]]
japanese_word = "趣味"
romaji = "shumi"
english_translation = "hobby"
category = "Noun"

[[translations]]
japanese_word = "お菓子"
romaji = "okashi"
english_translation = "sweets/snack"
category = "Noun"

[[translations]]
japanese_word = "和風"
romaji = "wafuu"
english_translation = "japanese style"
category = "Noun"

[[translations]]
japanese_word = "彼女"
romaji = "kanojo"
english_translation = "girlfriend"
category = "Noun"

[[translations]]
japanese_word = "彼氏"
romaji = "kareshi"
english_translation = "boyfriend"
category = "Noun"

[[translations]]
japanese_word = "子音"
romaji = "shiin"
english_translation = "consonant"
category = "Noun"

[[translations]]
japanese_word = "母音"
romaji = "boin"
english_translation = "vowel"
category = "Noun"

[[translations]]
japanese_word = "卓球"
romaji = "takkyuu"
english_translation = "table tennis"
category = "Noun"

[[translations]]
japanese_word = "数学"
romaji = "sugaku"
english_translation = "math"
category = "Noun"

[[translations]]
japanese_word = "中学校"
romaji = "chuugakkou"
english_translation = "middle school"
category = "Noun"

[[translations]]
japanese_word = "お祭り"
romaji = "omatsuri"
english_translation = "festival"
category = "Noun"

[[translations]]
japanese_word = "飛行機"
romaji = "hikouki"
english_translation = "plane"
category = "Noun"

[[translations]]
japanese_word = "自転車"
romaji = "jitensha"
english_translation = "bicycle"
category = "Noun"

[[translations]]
japanese_word = "オートバイ"
romaji = "otobai"
english_translation = "motorcycle (alive)"
category = "Noun"

[[translations]]
japanese_word = "卵"
romaji = "tamago"
english_translation = "egg"
category = "Noun"

[[translations]]
japanese_word = "庭鳥"
romaji = "niwa tori"
english_translation = "chicken (alive)"
category = "Noun"

[[translations]]
japanese_word = "チキン"
romaji = "chikin"
english_translation = "chicken (meat)"
category = "Noun"

[[translations]]
japanese_word = "君"
romaji = "kimi"
english_translation = "you"
category = "Noun"

[[translations]]
japanese_word = "国"
romaji = "koku"
english_translation = "country"
category = "Noun"

[[translations]]
japanese_word = "時間"
romaji = "jikan"
english_translation = "hour"
category = "Noun"

[[translations]]
japanese_word = "回転"
romaji = "kaiten"
english_translation = "spin"
category = "Noun"

[[translations]]
japanese_word = "方言"
romaji = "hogen"
english_translation = "dialect"
category = "Noun"

[[translations]]
japanese_word = "言葉"
romaji = "kotoba"
english_translation = "word"
category = "Noun"

[[translations]]
japanese_word = "牛乳"
romaji = "gyuunyuu"
english_translation = "milk"
category = "Noun"

[[translations]]
japanese_word = "チコ"
romaji = "chiko"
english_translation = "penis"
category = "Noun"

[[translations]]
japanese_word = "迷子"
romaji = "maigo"
english_translation = "lost"
category = "Noun"

[[translations]]
japanese_word = "見る"
romaji = "mimasu"
english_translation = "watch"
category = "Verb"

[[translations]]
japanese_word = "使います"
romaji = "tsukaimasu"
english_translation = "use"
category = "Verb"

[[translations]]
japanese_word = "書けます"
romaji = "kakemasu"
english_translation = "write"
category = "Verb"

[[translations]]
japanese_word = "作る"
romaji = "tsukuru"
english_translation = "make"
category = "Verb"

[[translations]]
japanese_word = "訪れる"
romaji = "otozureru"
english_translation = "visit"
category = "Verb"

[[translations]]
japanese_word = "思う"
romaji = "omou"
english_translation = "I think"
category = "Verb"

[[translations]]
japanese_word = "始まる"
romaji = "hajimaru"
english_translation = "start"
category = "Verb"

[[translations]]
japanese_word = "なるほど"
romaji = "naruhodo"
english_translation = "I see"
category = "Verb"

[[translations]]
japanese_word = "地獄"
romaji = "jigoku"
english_translation = "hell"
category = "Noun"

[[translations]]
japanese_word = "日中"
romaji = "nichibi"
english_translation = "midday"
category = "Time"

[[translations]]
japanese_word = "日没"
romaji = "nichibotsu"
english_translation = "sunset"
category = "Time"

[[translations]]
japanese_word = "一秒"
romaji = "ichi-byo"
english_translation = "one second"
category = "Time"

[[translations]]
japanese_word = "時"
romaji = "toki"
english_translation = "when (facts)"
category = "Time"

[[translations]]
japanese_word = "週末"
romaji = "shuumatsu"
english_translation = "weekend"
category = "Time"

[[translations]]
japanese_word = "何を"
romaji = "nani o"
english_translation = "what"
category = "Question"

[[translations]]
japanese_word = "いくつ"
romaji = "ikutsu"
english_translation = "how many"
category = "Question"

[[translations]]
japanese_word = "なぜ"
romaji = "naze"
english_translation = "why"
category = "Question"
